//*******************************************************************************
//*	cyrillic.jhf		Cyrillic
//*	formated for use with Arduino Processing 
//*	by Mark Sproul
//*******************************************************************************
//*	Feb  3,	2009	<MLS> Formated Hershey Cyrillic-1 for Arduino
//*******************************************************************************
//#include	"HersheyCyrillic1.h"


prog_char	gCyrillic1_00[]	PROGMEM	=	"Cyrillic-1";

/*2199*/	prog_char	gCyrillic1_20[]	PROGMEM	=	" 1JZ";
/*2214*/	prog_char	gCyrillic1_21[]	PROGMEM	=	"15MWRFQHRTSHRF RRHRN RRYQZR[SZRY";
/*2213*/	prog_char	gCyrillic1_22[]	PROGMEM	=	"14MWRMQNROSNRM RR[QZRYSZS\\R^Q_";
/*2275*/	prog_char	gCyrillic1_23[]	PROGMEM	=	"12H]SFLb RYFRb RLQZQ RKWYW";
/*2274*/	prog_char	gCyrillic1_24[]	PROGMEM	=	"42H\\PBP_ RTBT_ RXIWJXKYJYIWGTFPFMGKIKKLMMNOOUQWRYT RKKMMONUPWQXRYTYXWZT[P[MZKXKWLVMWLX";
/*2271*/	prog_char	gCyrillic1_25[]	PROGMEM	=	"32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT";
/*2272*/	prog_char	gCyrillic1_26[]	PROGMEM	=	"49F_[NZO[P\\O\\N[MZMYNXPVUTXRZP[M[JZIXIUJSPORMSKSIRGPFNGMIMKNNPQUXWZZ[[[\\Z\\Y RM[KZJXJUKSMQ RMKNMVXXZZ[";
/*2251*/	prog_char	gCyrillic1_27[]	PROGMEM	=	" 8MWRHQGRFSGSIRKQL";
/*2221*/	prog_char	gCyrillic1_28[]	PROGMEM	=	"20KYVBTDRGPKOPOTPYR]T`Vb RTDRHQKPPPTQYR\\T`";
/*2222*/	prog_char	gCyrillic1_29[]	PROGMEM	=	"20KYNBPDRGTKUPUTTYR]P`Nb RPDRHSKTPTTSYR\\P`";
/*2219*/	prog_char	gCyrillic1_2A[]	PROGMEM	=	" 9JZRFRR RMIWO RWIMO";
/*2232*/	prog_char	gCyrillic1_2B[]	PROGMEM	=	" 6E_RIR[ RIR[R";
/*2211*/	prog_char	gCyrillic1_2C[]	PROGMEM	=	" 8MWR[QZRYSZS\\R^Q_";
/*2231*/	prog_char	gCyrillic1_2D[]	PROGMEM	=	" 3E_IR[R";
/*2210*/	prog_char	gCyrillic1_2E[]	PROGMEM	=	" 6MWRYQZR[SZRY";
/*2220*/	prog_char	gCyrillic1_2F[]	PROGMEM	=	" 3G][BIb";

/*2200*/	prog_char	gCyrillic1_30[]	PROGMEM	=	"40H\\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF RQFOGNHMJLOLRMWNYOZQ[ RS[UZVYWWXRXOWJVHUGSF";
/*2201*/	prog_char	gCyrillic1_31[]	PROGMEM	=	"11H\\NJPISFS[ RRGR[ RN[W[";
/*2202*/	prog_char	gCyrillic1_32[]	PROGMEM	=	"45H\\LJMKLLKKKJLHMGPFTFWGXHYJYLXNUPPRNSLUKXK[ RTFVGWHXJXLWNTPPR RKYLXNXSZVZXYYX RNXS[W[XZYXYV";
/*2203*/	prog_char	gCyrillic1_33[]	PROGMEM	=	"47H\\LJMKLLKKKJLHMGPFTFWGXIXLWNTOQO RTFVGWIWLVNTO RTOVPXRYTYWXYWZT[P[MZLYKWKVLUMVLW RWQXTXWWYVZT[";
/*2204*/	prog_char	gCyrillic1_34[]	PROGMEM	=	"13H\\THT[ RUFU[ RUFJUZU RQ[X[";
/*2205*/	prog_char	gCyrillic1_35[]	PROGMEM	=	"39H\\MFKP RKPMNPMSMVNXPYSYUXXVZS[P[MZLYKWKVLUMVLW RSMUNWPXSXUWXUZS[ RMFWF RMGRGWF";
/*2206*/	prog_char	gCyrillic1_36[]	PROGMEM	=	"48H\\WIVJWKXJXIWGUFRFOGMILKKOKULXNZQ[S[VZXXYUYTXQVOSNRNOOMQLT RRFPGNIMKLOLUMXOZQ[ RS[UZWXXUXTWQUOSN";
/*2207*/	prog_char	gCyrillic1_37[]	PROGMEM	=	"31H\\KFKL RKJLHNFPFUIWIXHYF RLHNGPGUI RYFYIXLTQSSRVR[ RXLSQRSQVQ[";
/*2208*/	prog_char	gCyrillic1_38[]	PROGMEM	=	"63H\\PFMGLILLMNPOTOWNXLXIWGTFPF RPFNGMIMLNNPO RTOVNWLWIVGTF RPOMPLQKSKWLYMZP[T[WZXYYWYSXQWPTO RPONPMQLSLWMYNZP[ RT[VZWYXWXSWQVPTO";
/*2209*/	prog_char	gCyrillic1_39[]	PROGMEM	=	"48H\\XMWPURRSQSNRLPKMKLLINGQFSFVGXIYLYRXVWXUZR[O[MZLXLWMVNWMX RQSORMPLMLLMIOGQF RSFUGWIXLXRWVVXTZR[";
/*2212*/	prog_char	gCyrillic1_3A[]	PROGMEM	=	"12MWRMQNROSNRM RRYQZR[SZRY";
/*2213*/	prog_char	gCyrillic1_3B[]	PROGMEM	=	"14MWRMQNROSNRM RR[QZRYSZS\\R^Q_";
/*2241*/	prog_char	gCyrillic1_3C[]	PROGMEM	=	" 4F^ZIJRZ[";
/*2238*/	prog_char	gCyrillic1_3D[]	PROGMEM	=	" 6E_IO[O RIU[U";
/*2242*/	prog_char	gCyrillic1_3E[]	PROGMEM	=	" 4F^JIZRJ[";
/*2215*/	prog_char	gCyrillic1_3F[]	PROGMEM	=	"32I[MJNKMLLKLJMHNGPFSFVGWHXJXLWNVORQRT RSFUGVHWJWLVNTP RRYQZR[SZRY";

/*2273*/	prog_char	gCyrillic1_40[]	PROGMEM	=	"56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\\T]Q]O\\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV";
/*2801*/	prog_char	gCyrillic1_41[]	PROGMEM	=	"18H\\RFK[ RRFY[ RRIX[ RMUVU RI[O[ RU[[[";
/*2802*/	prog_char	gCyrillic1_42[]	PROGMEM	=	"31G]LFL[ RMFM[ RIFYFYLXF RMPUPXQYRZTZWYYXZU[I[ RUPWQXRYTYWXYWZU[";
/*2803*/	prog_char	gCyrillic1_43[]	PROGMEM	=	"45G]LFL[ RMFM[ RIFUFXGYHZJZLYNXOUP RUFWGXHYJYLXNWOUP RMPUPXQYRZTZWYYXZU[I[ RUPWQXRYTYWXYWZU[";
/*2804*/	prog_char	gCyrillic1_44[]	PROGMEM	=	"14I[NFN[ ROFO[ RKFZFZLYF RK[R[";
/*2805*/	prog_char	gCyrillic1_45[]	PROGMEM	=	"31F^NFNLMTLXKZJ[ RXFX[ RYFY[ RKF\\F RG[\\[ RG[Gb RH[Gb R[[\\b R\\[\\b";
/*2806*/	prog_char	gCyrillic1_46[]	PROGMEM	=	"22G\\LFL[ RMFM[ RSLST RIFYFYLXF RMPSP RI[Y[YUX[";
/*2807*/	prog_char	gCyrillic1_47[]	PROGMEM	=	"71CbRFR[ RSFS[ ROFVF RGGHHGIFHFGGFHFIGJIKMLONPWPYOZM[I\\G]F^F_G_H^I]H^G RNPLQKSJXIZH[ RNPMQLSKXJZI[G[FZEX RWPYQZS[X\\Z][ RWPXQYSZX[Z\\[^[_Z`X RO[V[";
/*2808*/	prog_char	gCyrillic1_48[]	PROGMEM	=	"45H\\LIKFKLLINGPFTFWGXIXLWNTOQO RTFVGWIWLVNTO RTOVPXRYTYWXYWZT[O[MZLYKWKVLUMVLW RWQXTXWWYVZT[";
/*2809*/	prog_char	gCyrillic1_49[]	PROGMEM	=	"27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\\F RXHLY RH[O[ RU[\\[";
/*2810*/	prog_char	gCyrillic1_4A[]	PROGMEM	=	"37F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\\F RXHLY RH[O[ RU[\\[ RN@N?M?M@NBPCTCVBW@";
/*2811*/	prog_char	gCyrillic1_4B[]	PROGMEM	=	"43F^KFK[ RLFL[ RHFOF RLPSPUOVMWIXGYFZF[G[HZIYHZG RSPUQVSWXXZY[ RSPTQUSVXWZX[Z[[Z\\X RH[O[";
/*2812*/	prog_char	gCyrillic1_4C[]	PROGMEM	=	"25E^MFMLLTKXJZI[H[GZGYHXIYHZ RXFX[ RYFY[ RJF\\F RU[\\[";
/*2813*/	prog_char	gCyrillic1_4D[]	PROGMEM	=	"30F_KFK[ RLFRX RKFR[ RYFR[ RYFY[ RZFZ[ RHFLF RYF]F RH[N[ RV[][";
/*2814*/	prog_char	gCyrillic1_4E[]	PROGMEM	=	"27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\\F RLPXP RH[O[ RU[\\[";
/*2815*/	prog_char	gCyrillic1_4F[]	PROGMEM	=	"44G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RQFOGMILKKOKRLVMXOZQ[ RS[UZWXXVYRYOXKWIUGSF";

/*2816*/	prog_char	gCyrillic1_50[]	PROGMEM	=	"21F^KFK[ RLFL[ RXFX[ RYFY[ RHF\\F RH[O[ RU[\\[";
/*2817*/	prog_char	gCyrillic1_51[]	PROGMEM	=	"29G]LFL[ RMFM[ RIFUFXGYHZJZMYOXPUQMQ RUFWGXHYJYMXOWPUQ RI[P[";
/*2818*/	prog_char	gCyrillic1_52[]	PROGMEM	=	"32G\\XIYLYFXIVGSFQFNGLIKKJNJSKVLXNZQ[S[VZXXYV RQFOGMILKKNKSLVMXOZQ[";
/*2819*/	prog_char	gCyrillic1_53[]	PROGMEM	=	"16I\\RFR[ RSFS[ RLFKLKFZFZLYF RO[V[";
/*2820*/	prog_char	gCyrillic1_54[]	PROGMEM	=	"24H]KFRV RLFSV RZFSVQYPZN[M[LZLYMXNYMZ RIFOF RVF\\F";
/*2821*/	prog_char	gCyrillic1_55[]	PROGMEM	=	"48F_RFR[ RSFS[ ROFVF RPILJJLIOIRJULWPXUXYW[U\\R\\O[LYJUIPI RPIMJKLJOJRKUMWPX RUXXWZU[R[OZLXJUI RO[V[";
/*2822*/	prog_char	gCyrillic1_56[]	PROGMEM	=	"21H\\KFX[ RLFY[ RYFK[ RIFOF RUF[F RI[O[ RU[[[";
/*2823*/	prog_char	gCyrillic1_57[]	PROGMEM	=	"27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\\F RH[\\[ R[[\\b R\\[\\b";
/*2824*/	prog_char	gCyrillic1_58[]	PROGMEM	=	"28F]KFKQLSOTRTUSWQ RLFLQMSOT RWFW[ RXFX[ RHFOF RTF[F RT[[[";
/*2825*/	prog_char	gCyrillic1_59[]	PROGMEM	=	"30BcGFG[ RHFH[ RRFR[ RSFS[ R]F][ R^F^[ RDFKF ROFVF RZFaF RD[a[";
/*2826*/	prog_char	gCyrillic1_5A[]	PROGMEM	=	"36BcGFG[ RHFH[ RRFR[ RSFS[ R]F][ R^F^[ RDFKF ROFVF RZFaF RD[a[ R`[ab Ra[ab";
/*2223*/	prog_char	gCyrillic1_5B[]	PROGMEM	=	"12KYOBOb RPBPb ROBVB RObVb";
/* 804*/	prog_char	gCyrillic1_5C[]	PROGMEM	=	" 3KYKFY^";
/*2224*/	prog_char	gCyrillic1_5D[]	PROGMEM	=	"12KYTBTb RUBUb RNBUB RNbUb";
/*2262*/	prog_char	gCyrillic1_5E[]	PROGMEM	=	"11JZPLRITL RMORJWO RRJR[";
/* 999*/	prog_char	gCyrillic1_5F[]	PROGMEM	=	" 3JZJ]Z]";

/*2252*/	prog_char	gCyrillic1_60[]	PROGMEM	=	" 8MWSFRGQIQKRLSKRJ";
/*2901*/	prog_char	gCyrillic1_61[]	PROGMEM	=	"39I]NONPMPMONNPMTMVNWOXQXXYZZ[ RWOWXXZZ[[[ RWQVRPSMTLVLXMZP[S[UZWX RPSNTMVMXNZP[";
/*2902*/	prog_char	gCyrillic1_62[]	PROGMEM	=	"48H\\XFWGQINKLNKQKULXNZQ[S[VZXXYUYSXPVNSMQMNNLPKS RXFWHUIQJNLLN RQMONMPLSLUMXOZQ[ RS[UZWXXUXSWPUNSM";
/*2903*/	prog_char	gCyrillic1_63[]	PROGMEM	=	"37H\\MMM[ RNMN[ RJMUMXNYPYQXSUT RUMWNXPXQWSUT RNTUTXUYWYXXZU[J[ RUTWUXWXXWZU[";
/*2904*/	prog_char	gCyrillic1_64[]	PROGMEM	=	"14HZMMM[ RNMN[ RJMXMXRWM RJ[Q[";
/*2905*/	prog_char	gCyrillic1_65[]	PROGMEM	=	"22F]NMNQMWLZK[ RWMW[ RXMX[ RKM[M RI[H`H[[[[`Z[";
/*2906*/	prog_char	gCyrillic1_66[]	PROGMEM	=	"31H[LSXSXQWOVNTMQMNNLPKSKULXNZQ[S[VZXX RWSWPVN RQMONMPLSLUMXOZQ[";
/*2907*/	prog_char	gCyrillic1_67[]	PROGMEM	=	"59E`RMR[ RSMS[ ROMVM RJNIOHNIMJMKNMRNSPTUTWSXRZN[M\\M]N\\O[N RPTNUMVKZJ[ RPTNVLZK[I[HZGX RUTWUXVZZ[[ RUTWVYZZ[\\[]Z^X RO[V[";
/*2908*/	prog_char	gCyrillic1_68[]	PROGMEM	=	"42I[MOLMLQMONNPMTMWNXPXQWSTT RTMVNWPWQVSTT RQTTTWUXWXXWZT[P[MZLXLWMVNWMX RTTVUWWWXVZT[";
/*2909*/	prog_char	gCyrillic1_69[]	PROGMEM	=	"27G]LML[ RMMM[ RWMW[ RXMX[ RIMPM RTM[M RI[P[ RT[[[ RWNMZ";
/*2910*/	prog_char	gCyrillic1_6A[]	PROGMEM	=	"37G]LML[ RMMM[ RWMW[ RXMX[ RIMPM RTM[M RI[P[ RT[[[ RWNMZ ROGOFNFNGOIQJSJUIVG";
/*2911*/	prog_char	gCyrillic1_6B[]	PROGMEM	=	"38H\\MMM[ RNMN[ RJMQM RNTPTSSTRVNWMXMYNXOWN RPTSUTVVZW[ RPTRUSVUZV[X[YZZX RJ[Q[";
/*2912*/	prog_char	gCyrillic1_6C[]	PROGMEM	=	"22G]NMNQMWLZK[J[IZJYKZ RWMW[ RXMX[ RKM[M RT[[[";
/*2913*/	prog_char	gCyrillic1_6D[]	PROGMEM	=	"30G^LML[ RLMR[ RMMRY RXMR[ RXMX[ RYMY[ RIMMM RXM\\M RI[O[ RU[\\[";
/*2914*/	prog_char	gCyrillic1_6E[]	PROGMEM	=	"27G]LML[ RMMM[ RWMW[ RXMX[ RIMPM RTM[M RMTWT RI[P[ RT[[[";
/*2915*/	prog_char	gCyrillic1_6F[]	PROGMEM	=	"36H\\QMNNLPKSKULXNZQ[S[VZXXYUYSXPVNSMQM RQMONMPLSLUMXOZQ[ RS[UZWXXUXSWPUNSM";

/*2916*/	prog_char	gCyrillic1_70[]	PROGMEM	=	"21G]LML[ RMMM[ RWMW[ RXMX[ RIM[M RI[P[ RT[[[";
/*2917*/	prog_char	gCyrillic1_71[]	PROGMEM	=	"36G\\LMLb RMMMb RMPONQMSMVNXPYSYUXXVZS[Q[OZMX RSMUNWPXSXUWXUZS[ RIMMM RIbPb";
/*2918*/	prog_char	gCyrillic1_72[]	PROGMEM	=	"28H[WPVQWRXQXPVNTMQMNNLPKSKULXNZQ[S[VZXX RQMONMPLSLUMXOZQ[";
/*2919*/	prog_char	gCyrillic1_73[]	PROGMEM	=	"16I\\RMR[ RSMS[ RMMLRLMYMYRXM RO[V[";
/*2920*/	prog_char	gCyrillic1_74[]	PROGMEM	=	"22I[LMR[ RMMRY RXMR[P_NaLbKbJaK`La RJMPM RTMZM";
/*2921*/	prog_char	gCyrillic1_75[]	PROGMEM	=	"52H]RFRb RSFSb ROFSF RRPQNPMNMLNKQKWLZN[P[QZRX RNMMNLQLWMZN[ RWMXNYQYWXZW[ RSPTNUMWMYNZQZWYZW[U[TZSX RObVb";
/*2922*/	prog_char	gCyrillic1_76[]	PROGMEM	=	"21H\\LMW[ RMMX[ RXML[ RJMPM RTMZM RJ[P[ RT[Z[";
/*2923*/	prog_char	gCyrillic1_77[]	PROGMEM	=	"23G]LML[ RMMM[ RWMW[ RXMX[ RIMPM RTM[M RI[[[[`Z[";
/*2924*/	prog_char	gCyrillic1_78[]	PROGMEM	=	"28G]LMLTMVPWRWUVWT RMMMTNVPW RWMW[ RXMX[ RIMPM RTM[M RT[[[";
/*2925*/	prog_char	gCyrillic1_79[]	PROGMEM	=	"30CbHMH[ RIMI[ RRMR[ RSMS[ R\\M\\[ R]M][ REMLM ROMVM RYM`M RE[`[";
/*2926*/	prog_char	gCyrillic1_7A[]	PROGMEM	=	"32CbHMH[ RIMI[ RRMR[ RSMS[ R\\M\\[ R]M][ REMLM ROMVM RYM`M RE[`[``_[";
/*2225*/	prog_char	gCyrillic1_7B[]	PROGMEM	=	"40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\\P^Q`RaTb";
/*2229*/	prog_char	gCyrillic1_7C[]	PROGMEM	=	" 3NVRBRb";
/*2226*/	prog_char	gCyrillic1_7D[]	PROGMEM	=	"40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\\T^S`RaPb";
/*2246*/	prog_char	gCyrillic1_7E[]	PROGMEM	=	"24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O";
/*2218*/	prog_char	gCyrillic1_7F[]	PROGMEM	=	"14KYQFOGNINKOMQNSNUMVKVIUGSFQF";

PGM_P gHershyCyrillic1FontTable[]	PROGMEM =
{

	gCyrillic1_00,
	gCyrillic1_20,
	gCyrillic1_21,
	gCyrillic1_22,
	gCyrillic1_23,
	gCyrillic1_24,
	gCyrillic1_25,
	gCyrillic1_26,
	gCyrillic1_27,
	gCyrillic1_28,
	gCyrillic1_29,
	gCyrillic1_2A,
	gCyrillic1_2B,
	gCyrillic1_2C,
	gCyrillic1_2D,
	gCyrillic1_2E,
	gCyrillic1_2F,

	gCyrillic1_30,
	gCyrillic1_31,
	gCyrillic1_32,
	gCyrillic1_33,
	gCyrillic1_34,
	gCyrillic1_35,
	gCyrillic1_36,
	gCyrillic1_37,
	gCyrillic1_38,
	gCyrillic1_39,
	gCyrillic1_3A,
	gCyrillic1_3B,
	gCyrillic1_3C,
	gCyrillic1_3D,
	gCyrillic1_3E,
	gCyrillic1_3F,

	gCyrillic1_40,
	gCyrillic1_41,
	gCyrillic1_42,
	gCyrillic1_43,
	gCyrillic1_44,
	gCyrillic1_45,
	gCyrillic1_46,
	gCyrillic1_47,
	gCyrillic1_48,
	gCyrillic1_49,
	gCyrillic1_4A,
	gCyrillic1_4B,
	gCyrillic1_4C,
	gCyrillic1_4D,
	gCyrillic1_4E,
	gCyrillic1_4F,

	gCyrillic1_50,
	gCyrillic1_51,
	gCyrillic1_52,
	gCyrillic1_53,
	gCyrillic1_54,
	gCyrillic1_55,
	gCyrillic1_56,
	gCyrillic1_57,
	gCyrillic1_58,
	gCyrillic1_59,
	gCyrillic1_5A,
	gCyrillic1_5B,
	gCyrillic1_5C,
	gCyrillic1_5D,
	gCyrillic1_5E,
	gCyrillic1_5F,

	gCyrillic1_60,
	gCyrillic1_61,
	gCyrillic1_62,
	gCyrillic1_63,
	gCyrillic1_64,
	gCyrillic1_65,
	gCyrillic1_66,
	gCyrillic1_67,
	gCyrillic1_68,
	gCyrillic1_69,
	gCyrillic1_6A,
	gCyrillic1_6B,
	gCyrillic1_6C,
	gCyrillic1_6D,
	gCyrillic1_6E,
	gCyrillic1_6F,

	gCyrillic1_70,
	gCyrillic1_71,
	gCyrillic1_72,
	gCyrillic1_73,
	gCyrillic1_74,
	gCyrillic1_75,
	gCyrillic1_76,
	gCyrillic1_77,
	gCyrillic1_78,
	gCyrillic1_79,
	gCyrillic1_7A,
	gCyrillic1_7B,
	gCyrillic1_7C,
	gCyrillic1_7D,
	gCyrillic1_7E,
	gCyrillic1_7F

};
